# -*- coding: utf-8 -*-
"""GENERATIVE AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zu3YaYpcEaYHjE0Wye_fVK2X3vdApqFV
"""

from transformers import pipeline
# load text generation model(GenAI)
generator = pipeline(
    "text-generation",
    model = "gpt2"
)
#Input prompt
prompt ="Artificial Intelligence in finance will"
result =generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated Text:")
print(result[0]['generated_text'])